In [1]:
import numpy as np

In [2]:
data2 = [[1,2,3,4], [5,6,7,]]

In [3]:
arr2 = np.array(data2)

In [4]:
print(arr2)

[list([1, 2, 3, 4]) list([5, 6, 7])]


In [5]:
list1 = [1,2,3]

In [6]:
arr1 = np.array(list1)

In [7]:
print(arr1)

[1 2 3]


In [8]:
type(arr1)

numpy.ndarray

In [9]:
my_numbers = [[6,5], [1,3], [5,6]]
sums = []

for row in my_numbers:
    row_sum = row[0] + row[1]
    sums.append(row_sum)
print(sums)
    

[11, 4, 11]


In [10]:
np.ones([4,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.zeros([11,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [15]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
np.random.randint(0,10,(4,4))

array([[1, 4, 9, 4],
       [4, 8, 2, 9],
       [2, 1, 8, 6],
       [0, 4, 8, 2]])

In [17]:
np.random.random((2,2,2))

array([[[0.34756493, 0.38593337],
        [0.68912503, 0.9494132 ]],

       [[0.83968595, 0.11033958],
        [0.80929536, 0.56832349]]])

In [18]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [19]:
np.full((6,7),9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [20]:
np.empty([4,4])

array([[4.67809131e-310, 0.00000000e+000, 2.33419537e-312,
        2.35541533e-312],
       [9.76118064e-313, 2.05833592e-312, 2.12199579e-312,
        2.33419537e-312],
       [8.48798317e-313, 9.33678148e-313, 1.01855798e-312,
        8.48798317e-313],
       [9.33678148e-313, 8.70018275e-313, 1.42167171e+161,
        6.93940207e+169]])

In [21]:
x = np.array([1,2,3])

In [22]:
x.ndim

1

In [23]:
x.shape

(3,)

In [24]:
x.size

3

In [25]:
x.itemsize

8

In [26]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x7f3dfe910910>, toplevel='numpy')>

In [27]:
x.nbytes

24

In [28]:
test_arr = np.random.randint(10, size=(5,5))

In [29]:
print(test_arr)

[[8 6 0 1 2]
 [5 4 8 9 6]
 [0 9 8 3 2]
 [2 1 2 8 1]
 [6 8 6 6 3]]


In [30]:
first_row = test_arr[0]

In [31]:
print(first_row)

[8 6 0 1 2]


In [32]:
print(test_arr[-1])

[6 8 6 6 3]


In [33]:
print(test_arr[1,2])

8


In [34]:
print(test_arr[1:3])

[[5 4 8 9 6]
 [0 9 8 3 2]]


In [35]:
print(test_arr[1:])

[[5 4 8 9 6]
 [0 9 8 3 2]
 [2 1 2 8 1]
 [6 8 6 6 3]]


In [36]:
np.nan

nan

In [37]:
np.pad

<function numpy.pad(array, pad_width, mode='constant', **kwargs)>

In [38]:
print(test_arr[:,1:3])

[[6 0]
 [4 8]
 [9 8]
 [1 2]
 [8 6]]


In [39]:
print(test_arr)

[[8 6 0 1 2]
 [5 4 8 9 6]
 [0 9 8 3 2]
 [2 1 2 8 1]
 [6 8 6 6 3]]


In [40]:
print(test_arr[1:4,:3])

[[5 4 8]
 [0 9 8]
 [2 1 2]]


In [41]:
print(test_arr[0,0])

8


In [42]:
x = np.array([1,2])

In [43]:
x

array([1, 2])

In [44]:
print(x.dtype)

int64


In [45]:
y = np.array([1.0, 2.0])

In [46]:
y

array([1., 2.])

In [47]:
print(y.dtype)

float64


In [48]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [49]:
def comute_reciprocals(values):
    output = np.empty(values)
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
        return output

In [50]:
np.random.seed(0)

In [51]:
values = np.random.randint(1,10,size=5)

In [52]:
print(comute_reciprocals(values))

[[[[[1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001
     1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001]
    [1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001
     1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001]
    [1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001
     1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001]
    [1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001
     1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001]]

   [[1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001
     1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001]
    [1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001
     1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001]
    [1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001
     1.66666667e-001 1.66666667e-001 1.66666667e-001 1.66666667e-001]
    [1.66666667e-001 1.66

In [53]:
l1 = [1,2,3]
l2 = [4,5,6]

In [54]:
l1+l2

[1, 2, 3, 4, 5, 6]

In [55]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [58]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
x = np.arange(9).reshape((3,3))

In [60]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [62]:
!head -n 10 data/nyc_taxis.csv

pickup_year,pickup_month,pickup_day,pickup_dayofweek,pickup_time,pickup_location_code,dropoff_location_code,trip_distance,trip_length,fare_amount,fees_amount,tolls_amount,tip_amount,total_amount,payment_type
2016,1,1,5,0,2,4,21.00,2037,52.00,0.80,5.54,11.65,69.99,1
2016,1,1,5,0,2,1,16.29,1520,45.00,1.30,0.00,8.00,54.30,1
2016,1,1,5,0,2,6,12.70,1462,36.50,1.30,0.00,0.00,37.80,2
2016,1,1,5,0,2,6,8.70,1210,26.00,1.30,0.00,5.46,32.76,1
2016,1,1,5,0,2,6,5.56,759,17.50,1.30,0.00,0.00,18.80,2
2016,1,1,5,0,4,2,21.45,2004,52.00,0.80,0.00,52.80,105.60,1
2016,1,1,5,0,2,6,8.45,927,24.50,1.30,0.00,6.45,32.25,1
2016,1,1,5,0,2,6,7.30,731,21.50,1.30,0.00,0.00,22.80,2
2016,1,1,5,0,2,5,36.30,2562,109.50,0.80,11.08,10.00,131.38,1


In [63]:
import csv

In [64]:
with open('data/nyc_taxis.csv', 'r') as f:
    taxi_list = list(csv.reader(f))

In [65]:
taxi_list[:4]

[['pickup_year',
  'pickup_month',
  'pickup_day',
  'pickup_dayofweek',
  'pickup_time',
  'pickup_location_code',
  'dropoff_location_code',
  'trip_distance',
  'trip_length',
  'fare_amount',
  'fees_amount',
  'tolls_amount',
  'tip_amount',
  'total_amount',
  'payment_type'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '4',
  '21.00',
  '2037',
  '52.00',
  '0.80',
  '5.54',
  '11.65',
  '69.99',
  '1'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '1',
  '16.29',
  '1520',
  '45.00',
  '1.30',
  '0.00',
  '8.00',
  '54.30',
  '1'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '6',
  '12.70',
  '1462',
  '36.50',
  '1.30',
  '0.00',
  '0.00',
  '37.80',
  '2']]

In [66]:
taxi_list[2:]

[['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '1',
  '16.29',
  '1520',
  '45.00',
  '1.30',
  '0.00',
  '8.00',
  '54.30',
  '1'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '6',
  '12.70',
  '1462',
  '36.50',
  '1.30',
  '0.00',
  '0.00',
  '37.80',
  '2'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '6',
  '8.70',
  '1210',
  '26.00',
  '1.30',
  '0.00',
  '5.46',
  '32.76',
  '1'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '6',
  '5.56',
  '759',
  '17.50',
  '1.30',
  '0.00',
  '0.00',
  '18.80',
  '2'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '4',
  '2',
  '21.45',
  '2004',
  '52.00',
  '0.80',
  '0.00',
  '52.80',
  '105.60',
  '1'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '6',
  '8.45',
  '927',
  '24.50',
  '1.30',
  '0.00',
  '6.45',
  '32.25',
  '1'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '6',
  '7.30',
  '731',
  '21.50',
  '1.30',
  '0.00',
  '0.00',
  '22.80',
  '2'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '5',
  '36.30',
  '2562',
 

In [67]:
converted_taxi_list = []

for row in taxi_list:
    converted_row = []
    for item in row:
        try:
            converted_row.append(float(item))
        except:
            continue
    converted_taxi_list.append(converted_row)

In [68]:
converted_taxi_list[:2]

[[],
 [2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  4.0,
  21.0,
  2037.0,
  52.0,
  0.8,
  5.54,
  11.65,
  69.99,
  1.0]]

In [69]:
taxi = np.array(converted_taxi_list)

In [70]:
taxi

array([list([]),
       list([2016.0, 1.0, 1.0, 5.0, 0.0, 2.0, 4.0, 21.0, 2037.0, 52.0, 0.8, 5.54, 11.65, 69.99, 1.0]),
       list([2016.0, 1.0, 1.0, 5.0, 0.0, 2.0, 1.0, 16.29, 1520.0, 45.0, 1.3, 0.0, 8.0, 54.3, 1.0]),
       ...,
       list([2016.0, 6.0, 30.0, 4.0, 5.0, 2.0, 6.0, 12.76, 1083.0, 34.5, 1.3, 0.0, 8.95, 44.75, 1.0]),
       list([2016.0, 6.0, 30.0, 4.0, 5.0, 2.0, 0.0, 17.54, 1711.0, 48.0, 1.3, 5.54, 0.0, 54.84, 2.0]),
       list([])], dtype=object)

In [71]:
type(taxi)

numpy.ndarray

In [72]:
taxi_shape = taxi.shape

In [73]:
print(taxi_shape)

(89562,)


In [74]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [75]:
x + y

array([5, 7, 9])

In [76]:
x - y

array([-3, -3, -3])

In [77]:
x * y

array([ 4, 10, 18])

In [78]:
x / y

array([0.25, 0.4 , 0.5 ])

In [79]:
x ** 2

array([1, 4, 9])

In [80]:
x.dot(y)

32

In [81]:
z = np.array([y, y**2])

In [82]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [83]:
z.sort()

In [84]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [85]:
z.shape

(2, 3)

In [86]:
taxi.size

89562

In [87]:
with open('data/nyc_taxis.csv', 'r') as f:
    taxi_list = list(csv.reader(f))

In [88]:
taxi_list[:4]

[['pickup_year',
  'pickup_month',
  'pickup_day',
  'pickup_dayofweek',
  'pickup_time',
  'pickup_location_code',
  'dropoff_location_code',
  'trip_distance',
  'trip_length',
  'fare_amount',
  'fees_amount',
  'tolls_amount',
  'tip_amount',
  'total_amount',
  'payment_type'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '4',
  '21.00',
  '2037',
  '52.00',
  '0.80',
  '5.54',
  '11.65',
  '69.99',
  '1'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '1',
  '16.29',
  '1520',
  '45.00',
  '1.30',
  '0.00',
  '8.00',
  '54.30',
  '1'],
 ['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '6',
  '12.70',
  '1462',
  '36.50',
  '1.30',
  '0.00',
  '0.00',
  '37.80',
  '2']]

In [89]:
print(taxi_list[:3])

[['pickup_year', 'pickup_month', 'pickup_day', 'pickup_dayofweek', 'pickup_time', 'pickup_location_code', 'dropoff_location_code', 'trip_distance', 'trip_length', 'fare_amount', 'fees_amount', 'tolls_amount', 'tip_amount', 'total_amount', 'payment_type'], ['2016', '1', '1', '5', '0', '2', '4', '21.00', '2037', '52.00', '0.80', '5.54', '11.65', '69.99', '1'], ['2016', '1', '1', '5', '0', '2', '1', '16.29', '1520', '45.00', '1.30', '0.00', '8.00', '54.30', '1']]


In [90]:
taxi_list = taxi_list[1:]

In [91]:
print(taxi_list[1:])

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [92]:


converted_taxi_list = []

for row in taxi_list:
    converted_row = []
    for item in row:
        try:
            converted_row.append(float(item))
        except:
            continue
    converted_taxi_list.append(converted_row)



In [93]:
taxi = np.array(converted_taxi_list)

In [94]:
taxi.shape

(89561,)

In [95]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [96]:
taxi = np.genfromtxt('data/nyc_taxis.csv', delimiter=',')

In [97]:
taxi[:4]

array([[      nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
        1.165e+01, 6.999e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        1.000e+00, 1.629e+01, 1.520e+03, 4.500e+01, 1.300e+00, 0.000e+00,
        8.000e+00, 5.430e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 1.270e+01, 1.462e+03, 3.650e+01, 1.300e+00, 0.000e+00,
        0.000e+00, 3.780e+01, 2.000e+00]])

In [98]:
taxi.shape

(89561, 15)

In [99]:
taxi[2:]

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 5.460e+00, 3.276e+01,
        1.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [100]:
taxi.shape

(89561, 15)

In [101]:
taxi.T

array([[      nan, 2.016e+03, 2.016e+03, ..., 2.016e+03, 2.016e+03,
        2.016e+03],
       [      nan, 1.000e+00, 1.000e+00, ..., 6.000e+00, 6.000e+00,
        6.000e+00],
       [      nan, 1.000e+00, 1.000e+00, ..., 3.000e+01, 3.000e+01,
        3.000e+01],
       ...,
       [      nan, 1.165e+01, 8.000e+00, ..., 5.000e+00, 8.950e+00,
        0.000e+00],
       [      nan, 6.999e+01, 5.430e+01, ..., 6.334e+01, 4.475e+01,
        5.484e+01],
       [      nan, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        2.000e+00]])

In [102]:
col1 = taxi[:, 6]
col2 = taxi[:, 8]
col3 = taxi[:, 11]

In [103]:
sums = col1 + col2 + col3

In [104]:
sums

array([    nan, 2046.54, 1521.  , ..., 2831.54, 1089.  , 1716.54])

In [105]:
taxi.shape

(89561, 15)

In [106]:
trip_distance = taxi[:, 5]
trip_price = taxi[:, 12]

In [107]:
price_per_mile = trip_price / trip_distance

<ipython-input-107-b4363ea3de3d>:1: RuntimeWarning: divide by zero encountered in true_divide
  price_per_mile = trip_price / trip_distance
<ipython-input-107-b4363ea3de3d>:1: RuntimeWarning: invalid value encountered in true_divide
  price_per_mile = trip_price / trip_distance


In [108]:
price_per_mile

array([  nan, 5.825, 4.   , ..., 2.5  , 4.475, 0.   ])

In [109]:
np.array([1,2,3]) / 0

<ipython-input-109-c1ea26be6b27>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([1,2,3]) / 0


array([inf, inf, inf])

In [110]:
price_per_mile2 = np.divide(trip_price, trip_distance)

<ipython-input-110-fe4563909266>:1: RuntimeWarning: divide by zero encountered in true_divide
  price_per_mile2 = np.divide(trip_price, trip_distance)
<ipython-input-110-fe4563909266>:1: RuntimeWarning: invalid value encountered in true_divide
  price_per_mile2 = np.divide(trip_price, trip_distance)


In [111]:
price_per_mile2

array([  nan, 5.825, 4.   , ..., 2.5  , 4.475, 0.   ])

In [112]:
price_min = taxi[:, 12].min()

In [113]:
price_min

nan

In [114]:
price_max = taxi[:, 12].max()

In [115]:
price_max

nan

In [116]:
print(taxi.dtype)

float64


In [117]:
taxi = taxi[1:]

In [118]:
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [119]:
taxi = np.genfromtxt('data/nyc_taxis.csv', delimiter=',', skip_header = 1)

In [120]:
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [121]:
taxi.shape

(89560, 15)

In [122]:
arr = np.zeros(10)

In [123]:
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [124]:
arr[4] = 1

In [125]:
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [126]:
ra = np.arange(10,50)

In [127]:
print(ra)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [128]:
ra = np.arange(10,50)[::-1]

In [129]:
ra

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [130]:
np.random.randint(0,8,(3,3))

array([[1, 3, 5],
       [2, 4, 7],
       [6, 0, 0]])

In [131]:
a = [1,2,0,0,4,0]

In [132]:
def indi(x):
    for i,j in enumerate (a):
        if i[j] != 0:
            return i, j

In [133]:
a = [1,2,0,0,4,0]

for i,j in enumerate (a):
    if j != 0:
        x = np.array([i])
        print(f'{np.array([i])} {x.dtype}')

[0] int64
[1] int64
[4] int64


In [134]:
a = [1,2,0,0,4,0]
r = np.array(a)
print(r)
x = np.nonzero(r)
print((x), r.dtype)

[1 2 0 0 4 0]
(array([0, 1, 4]),) int64


In [135]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [136]:
print(np.random.random((3,3,3)))

[[[0.27265629 0.47766512 0.81216873]
  [0.47997717 0.3927848  0.83607876]
  [0.33739616 0.64817187 0.36824154]]

 [[0.95715516 0.14035078 0.87008726]
  [0.47360805 0.80091075 0.52047748]
  [0.67887953 0.72063265 0.58201979]]

 [[0.53737323 0.75861562 0.10590761]
  [0.47360042 0.18633234 0.73691818]
  [0.21655035 0.13521817 0.32414101]]]


In [137]:
print(np.random.random((10,10)))

[[0.14967487 0.22232139 0.38648898 0.90259848 0.44994999 0.61306346
  0.90234858 0.09928035 0.96980907 0.65314004]
 [0.17090959 0.35815217 0.75068614 0.60783067 0.32504723 0.03842543
  0.63427406 0.95894927 0.65279032 0.63505887]
 [0.99529957 0.58185033 0.41436859 0.4746975  0.6235101  0.33800761
  0.67475232 0.31720174 0.77834548 0.94957105]
 [0.66252687 0.01357164 0.6228461  0.67365963 0.971945   0.87819347
  0.50962438 0.05571469 0.45115921 0.01998767]
 [0.44171092 0.97958673 0.35944446 0.48089353 0.68866118 0.88047589
  0.91823547 0.21682214 0.56518887 0.86510256]
 [0.50896896 0.91672295 0.92115761 0.08311249 0.27771856 0.0093567
  0.84234208 0.64717414 0.84138612 0.26473016]
 [0.39782075 0.55282148 0.16494046 0.36980809 0.14644176 0.56961841
  0.70373728 0.28847644 0.43328806 0.75610669]
 [0.39609828 0.89603839 0.63892108 0.89155444 0.68005557 0.44919774
  0.97857093 0.11620191 0.7670237  0.41182014]
 [0.67543908 0.24979628 0.31321833 0.96541622 0.58846509 0.65966841
  0.53320625 

In [138]:
x = np.random.random((10,10))

In [139]:
x

array([[5.51816259e-01, 3.36250935e-02, 9.68961765e-01, 3.20997241e-01,
        2.21262685e-01, 1.41263905e-01, 9.72599271e-02, 9.84042241e-01,
        2.60340928e-01, 5.37022521e-01],
       [4.47926172e-01, 9.95690891e-02, 3.52311661e-01, 4.69249174e-01,
        8.41140130e-01, 9.04647744e-01, 3.75593838e-02, 5.08315449e-01,
        1.66847513e-01, 7.79051020e-01],
       [8.64933296e-01, 4.11396724e-01, 1.39972585e-01, 3.32223853e-02,
        9.82574960e-01, 3.73290751e-01, 4.20075370e-01, 5.05881151e-02,
        3.65496106e-01, 1.66279737e-02],
       [2.30742335e-01, 7.64911699e-01, 9.44123519e-01, 7.49999249e-01,
        3.39403819e-01, 4.89548937e-01, 3.38985117e-01, 1.79490261e-01,
        1.70986599e-01, 4.63450977e-01],
       [8.74572958e-01, 9.44119751e-01, 6.08252866e-01, 5.96655406e-01,
        7.83644245e-01, 5.00026298e-01, 5.03700568e-02, 6.99098075e-01,
        9.92396399e-01, 2.67262538e-01],
       [6.79090616e-01, 8.64281443e-01, 7.50844246e-01, 9.64489768e-01,
   

In [140]:
x.min()

5.535686500857118e-05

In [141]:
x.max()

0.9923963988886326

In [142]:
d = np.ones((10,10))
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [143]:
d[1:-1, 1:-1] = 0

In [144]:
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [145]:
0 * np.nan

nan

In [146]:
np.nan

nan

In [147]:
np.nan == np.nan

False

In [148]:
np.inf > np.nan

False

In [149]:
np.inf

inf

In [150]:
np.nan - np.nan

nan

In [151]:
0.3 == 3 * 0.1

False

In [152]:
q = np.zeros((8,8))

In [153]:
print(q)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [154]:
d[1::2, ::2] = 1
d[::2, 1::2] = 1

In [155]:
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [156]:
Z = np.arange(11)

In [157]:
#print(Z[4:9]*-1)

In [158]:
Z = np.arange(11)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [159]:
r = (Z[4:9])
z[r] *= -1

IndexError: index -4 is out of bounds for axis 0 with size 2

In [ ]:
print(r)

In [ ]:
r = (Z[4:9] * (-1))

In [ ]:
print(r)

In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

In [ ]:
np.linspace(0,1,10, endpoint=False)[1:]

In [ ]:
np.linspace(0,1,10)

In [ ]:
s = np.random.random(10)

In [ ]:
s

In [ ]:
s.sort()

In [ ]:
s

In [ ]:
A = np.random.randint(0,2,5)

In [ ]:
A

In [ ]:
B = np.random.randint(0,2,5)

In [ ]:
B

In [ ]:
Z = np.zeros(10)

In [ ]:
Z

In [ ]:
Z.flags.writeable = False

In [ ]:
Z

In [ ]:
Z[0] = 1

In [ ]:
T = np.random.random(10)

In [ ]:
T

In [ ]:
T.max()

In [ ]:
T[T.argmax()] = 0

In [ ]:
T

In [ ]:
Z = np.arange(100)

In [ ]:
Z

In [ ]:
v = np.random.uniform(0,100)

In [ ]:
v

In [ ]:
index = (np.abs(Z-v)).argmin()
print(Z[index])

In [160]:
Z = np.arange(10, dtype=np.int32)

In [161]:
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [162]:
Z = np.arange(10, dtype=np.float32)

In [163]:
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [164]:
Z = np.random.randint(0,10,50)
print(Z)

[5 0 8 5 4 7 4 1 3 3 9 2 5 2 3 5 7 2 7 1 6 5 0 0 3 1 9 9 6 6 7 8 8 7 0 8 6
 8 9 8 3 6 1 7 4 9 2 0 8 2]


In [166]:
np.bincount(Z)

array([5, 4, 5, 5, 3, 5, 5, 6, 7, 5])